// Aquí puedes editar las fotos, nombres y el detalle/edad del perrito, solo necesitas reemplazar la información cuando necesites actualizar
const CACHORROS = [
  { img: "images/g01_yorkshire.jpeg", nombre: "Yorkshire Terrier Mini", detalle: "Macho\n2 meses" },
  { img: "images/g02_caniche_exotica.jpeg", nombre: "Caniche Linea Exótica", detalle: "Hembra\n2 meses" },
  { img: "images/g03_goldendoodle.jpg", nombre: "💫Goldendoodle💫", detalle: "Macho\n2 meses" },
  { img: "images/g04_goldendoodle.png", nombre: "Goldendoodle", detalle: "Hembra\n2 meses" },
  { img: "images/g05_caniche_mini_chocolate.jpeg", nombre: "💫Caniche Mini Chocolate💫", detalle: "Macho\n2 meses" },
  { img: "images/g06_goldendoodle_dorado.jpeg", nombre: "Goldendoodle Dorado", detalle: "Hembra\n2 meses" },
  { img: "images/g07_cocker.jpeg", nombre: "Cocker Spaniel", detalle: "Hembra y Macho\n2 meses" },
  { img: "images/g08_goldendoodle.jpg", nombre: "Goldendoodle", detalle: "Hembra\n2 meses" },
  { img: "images/g09_schnauzer.jpeg", nombre: "Schnauzer", detalle: "🥰Tu casa estará llena de diversión💓" },
  { img: "images/g10_gato_esfinge.jpeg", nombre: "Gato Esfinge", detalle: "🥰😍💫Cuenta con nuestra garantía y cordialidad" },
  { img: "images/g11_goldendoodle.jpeg", nombre: "Goldendoodle", detalle: "✨Tu amigo leal desde que se aprecian✨" },
  { img: "images/g12_pomerania.jpeg", nombre: "Pomerania", detalle: "🏡🐶 Convierte tu casa en un hogar lleno de alegría y ternura." },
  { img: "images/g13_pomerania_mini.jpeg", nombre: "Pomerania mini", detalle: "🐾Un cachorro, una nueva familia. Gracias por confiar en Willin Mascotas 💛🐶" },
  { img: "images/g14_goldendoodle.jpeg", nombre: "Goldendoodle", detalle: "🐾 Amor a primera huellita 💖" },
  { img: "images/g15_pequines.jpeg", nombre: "Pequinés", detalle: "🐶 Nuevo integrante, nueva felicidad ✨" },
  { img: "images/g16_goldendoodle.jpeg", nombre: "Goldendoodle", detalle: "🐶 Momentos que se vuelven eternos ✨" },
  { img: "images/g17_chihuahua.jpeg", nombre: "Chihuahua", detalle: "💫 Más que una mascota, un amigo" },
  { img: "images/g18_maltipoo.jpeg", nombre: "Maltipoo", detalle: "🐶 Una conexión única 💖" },
  { img: "images/g19_schnauzer.jpeg", nombre: "Schnauzer", detalle: "🐾 Amor que se siente desde el primer abrazo 🤗" },
  { img: "images/g20_cocker.jpeg", nombre: "Cocker Spaniel", detalle: "⭐ Perfecto compañero de vida 💕" },
  { img: "images/g21_golden_retriever.jpeg", nombre: "Golden Retriver", detalle: "Más patitas, más felicidad 🐾✨" },
  { img: "images/g22_goldendoodle.jpeg", nombre: "Goldendoodle", detalle: "Bienvenido a casa, pequeño torbellino 🐾💛" },
  { img: "images/g23_shihtzu.jpeg", nombre: "Shih Tzu", detalle: "Llegó el nuevo rey de los mimos 👑🐶" },
  { img: "images/g24_bulldog_frances.jpeg", nombre: "Bulldog Francés", detalle: "Un maravilloso regalo del día de la madre👑" },
  { img: "images/g25_schnauzer.jpeg", nombre: "Schnauzer", detalle: "🏡 Un nuevo hogar, una nueva aventura 🐕" },
  { img: "images/g26_schnauzer.jpeg", nombre: "Schnauzer", detalle: "🐶 Clientes felices, corazones felices ✨" },
  { img: "images/g27_schnauzer.jpeg", nombre: "Schnauzer", detalle: "🐾 Amor peludo en casa 💖" },
  { img: "images/g28_pincher_chocolate.jpeg", nombre: "Pincher Chocolate", detalle: "✨ Felicidad con cuatro patas 🐶" },
  { img: "images/g29_caniche_apricot.jpeg", nombre: "Caniche mini Apricot", detalle: "💫Entregamos cachorros de calidad💫" },
  { img: "images/g30_golden_retriever.jpeg", nombre: "Golden Retriever", detalle: "💫Mini aventura con grandes huellas💫" }
];
